# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0529f30c446509813a822691f1a1637c8c81539a29ffb5b7c5350519c3d5c50ff11d24115570ea73ec0211bd00a1bffc8d186b7f13508e352468362527ff0a19
  consumer_key        : <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret     : <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  access_token        : <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  access_token_secret : <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>

test:
  secret_key_base: 2d5315d06d9b66e6caa39ef442ac4b68d0090b7cc49100139bb892b597b37cefd7091e5cf9bc52ee16f21f3f7cd4a895d91d44a2070d054193944ebb4bf0801d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
